{
  "formatVersion": "1.1",
  "component": {
    "group": "atonkish.reinfshulker",
    "module": "reinforced-shulker-boxes",
    "version": "1.1.5+1.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "reinforced-shulker-boxes-1.1.5+1.17.jar",
          "url": "reinforced-shulker-boxes-1.1.5+1.17.jar",
          "size": 424874,
          "sha512": "257ab362a3c94e4c0d0f08205914419c2478a2e2a741f4f551d79b1b55901a723b3ab9d1940fc8e29293a2cbba5e252621f3ae5c70b9d5860693e9d71f221de1",
          "sha256": "b83a053b0e558fc2bf4a9085c4e4aaf1a8407e0fa1e932f86247e09040f18526",
          "sha1": "2052c93c66f3583f1072a937fdb8a532d613bc87",
          "md5": "613dea3dd7d7814f28f5c8a0718eb00a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "blue.endless",
          "module": "jankson",
          "version": {
            "requires": "1.2.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.12.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.44.0+1.17"
          }
        },
        {
          "group": "atonkish.reinfcore",
          "module": "reinforced-core",
          "version": {
            "requires": "1.1.1+1.17"
          }
        },
        {
          "group": "net.kyrptonaught",
          "module": "quickshulker",
          "version": {
            "requires": "1.3.0-1.17"
          }
        },
        {
          "group": "com.misterpemodder",
          "module": "shulkerboxtooltip",
          "version": {
            "requires": "3.0.4+1.17.1"
          }
        }
      ],
      "files": [
        {
          "name": "reinforced-shulker-boxes-1.1.5+1.17.jar",
          "url": "reinforced-shulker-boxes-1.1.5+1.17.jar",
          "size": 424874,
          "sha512": "257ab362a3c94e4c0d0f08205914419c2478a2e2a741f4f551d79b1b55901a723b3ab9d1940fc8e29293a2cbba5e252621f3ae5c70b9d5860693e9d71f221de1",
          "sha256": "b83a053b0e558fc2bf4a9085c4e4aaf1a8407e0fa1e932f86247e09040f18526",
          "sha1": "2052c93c66f3583f1072a937fdb8a532d613bc87",
          "md5": "613dea3dd7d7814f28f5c8a0718eb00a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "reinforced-shulker-boxes-1.1.5+1.17-sources.jar",
          "url": "reinforced-shulker-boxes-1.1.5+1.17-sources.jar",
          "size": 373073,
          "sha512": "85ce4061d6a185b37607e71858bd87a011fb0f682bb77f316071bc99dcc1ff661dd6adb16e19a8f8b1a915a1fe1099a427e508ae9f37bb501d7d57843f348da9",
          "sha256": "45535c8167b107e818037eceede0b8e9b34a21d22d40e61cd7a9c0a482da71ce",
          "sha1": "4bd8e99f22c3b47bbf2d898f8694857dc5091689",
          "md5": "a3c206b266e0cc0fe051e6007cd5eb49"
        }
      ]
    }
  ]
}
