{
  "formatVersion": "1.1",
  "component": {
    "group": "atonkish.reinfcore",
    "module": "reinforced-core",
    "version": "3.0.5+1.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "blue.endless",
          "module": "jankson",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.27"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "9.0.94"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "reinforced-core-3.0.5+1.19.jar",
          "url": "reinforced-core-3.0.5+1.19.jar",
          "size": 1037503,
          "sha512": "ce82c8f3537bb4be2c5362e00854849e47006441bc60f0c9872e26258a38187ee37f89d417cd578cfe3600e0750a7be62d1cf3226e2b17a5e5a8fb5e738746a6",
          "sha256": "17b72c2ebc92bda6487e2a9d8260e4d11dd776935b4223f9389e5ce6337605e1",
          "sha1": "dbefa2b0585d748788453d112d77792eea4f629b",
          "md5": "73c10487cf019c00dd47537574e53bb7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "blue.endless",
          "module": "jankson",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.27"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "9.0.94"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.14"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.74.0+1.19.3"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "5.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "reinforced-core-3.0.5+1.19.jar",
          "url": "reinforced-core-3.0.5+1.19.jar",
          "size": 1037503,
          "sha512": "ce82c8f3537bb4be2c5362e00854849e47006441bc60f0c9872e26258a38187ee37f89d417cd578cfe3600e0750a7be62d1cf3226e2b17a5e5a8fb5e738746a6",
          "sha256": "17b72c2ebc92bda6487e2a9d8260e4d11dd776935b4223f9389e5ce6337605e1",
          "sha1": "dbefa2b0585d748788453d112d77792eea4f629b",
          "md5": "73c10487cf019c00dd47537574e53bb7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "reinforced-core-3.0.5+1.19-sources.jar",
          "url": "reinforced-core-3.0.5+1.19-sources.jar",
          "size": 28427,
          "sha512": "b654b524f9588f4bc3d0b1be0ae1fe46c44bf6fca9a2ab67fb12bab82dd850292c2979bf5f74732f8d157e4e1e9cfbe1c4f838048082d0ded25cca2e5d71f3bd",
          "sha256": "9b2f4dc2b3fb05afe7d12fb6e4d1f186134622108e1b02bd75dfd880c3edc7dc",
          "sha1": "de97acf3fc3fcffcd92ce0fef24c706d7fc43673",
          "md5": "93a5513e5f91ea15674c5defb9beb99a"
        }
      ]
    }
  ]
}
