{
  "formatVersion": "1.1",
  "component": {
    "group": "atonkish.reinfcore",
    "module": "reinforced-core",
    "version": "4.0.1+1.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "15.0.127"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "reinforced-core-4.0.1+1.21.jar",
          "url": "reinforced-core-4.0.1+1.21.jar",
          "size": 1045442,
          "sha512": "43b2848d0fcddf094de7a9d43a57658417b772996b0c2694c530b15f623f81d1bd6b47cb9581ce9d9fcd78f841c755d307d9c3a5efc19134fb5b0a9b9e5b5724",
          "sha256": "70014402e0c61b1b4c33519be84a472c55dc57a65fc1bcfcf8d723719923874d",
          "sha1": "1a52bb795b71100557f55eacd77fd96564069d57",
          "md5": "ec3f857d38cd068ee089f03623252e3b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "15.0.127"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.100.1+1.21"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "11.0.0-rc.2"
          }
        }
      ],
      "files": [
        {
          "name": "reinforced-core-4.0.1+1.21.jar",
          "url": "reinforced-core-4.0.1+1.21.jar",
          "size": 1045442,
          "sha512": "43b2848d0fcddf094de7a9d43a57658417b772996b0c2694c530b15f623f81d1bd6b47cb9581ce9d9fcd78f841c755d307d9c3a5efc19134fb5b0a9b9e5b5724",
          "sha256": "70014402e0c61b1b4c33519be84a472c55dc57a65fc1bcfcf8d723719923874d",
          "sha1": "1a52bb795b71100557f55eacd77fd96564069d57",
          "md5": "ec3f857d38cd068ee089f03623252e3b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "reinforced-core-4.0.1+1.21-sources.jar",
          "url": "reinforced-core-4.0.1+1.21-sources.jar",
          "size": 29866,
          "sha512": "553a513884257f7f4914f08d459c0f9db976361a78019f4885d37bde5b0d169049eacc24eef6be5f6e3c7b0bf66d133571358d4a5544885ec4b9b4dd724b8872",
          "sha256": "150e6bce948cc93b3b120e90df6801ee63357eee7d25f87c30186600b3ed180c",
          "sha1": "e2e12c53fa30d9e5dea2a5754e23a1b018c6268d",
          "md5": "6093c35f251de0037b448f8b28811407"
        }
      ]
    }
  ]
}
