{
  "formatVersion": "1.1",
  "component": {
    "group": "atonkish.reinfcore",
    "module": "reinforced-core",
    "version": "3.1.2+1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "11.0.99"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "reinforced-core-3.1.2+1.20.jar",
          "url": "reinforced-core-3.1.2+1.20.jar",
          "size": 1042266,
          "sha512": "b0bf38068ad010fb229d45ab592700afa77669d0e3c920e67f1c6b372b2c2fa2c7a8e1dfe628f0f9dadc104452e9b00c67db7efb88151c2341ef5b1029758299",
          "sha256": "9098d962c48c69d5dc7c2c68b22d7737fe7fa8825eaf1333e6592ba8667ce707",
          "sha1": "7e692fef2219b3fd0983c929220c9c64cc9c5126",
          "md5": "a4f4ea623c392a1663e5292eff9e1ba8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "11.0.99"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.83.1+1.20.1"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "reinforced-core-3.1.2+1.20.jar",
          "url": "reinforced-core-3.1.2+1.20.jar",
          "size": 1042266,
          "sha512": "b0bf38068ad010fb229d45ab592700afa77669d0e3c920e67f1c6b372b2c2fa2c7a8e1dfe628f0f9dadc104452e9b00c67db7efb88151c2341ef5b1029758299",
          "sha256": "9098d962c48c69d5dc7c2c68b22d7737fe7fa8825eaf1333e6592ba8667ce707",
          "sha1": "7e692fef2219b3fd0983c929220c9c64cc9c5126",
          "md5": "a4f4ea623c392a1663e5292eff9e1ba8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
