{
  "formatVersion": "1.1",
  "component": {
    "group": "atonkish.reinfchest",
    "module": "reinforced-chests",
    "version": "2.4.4+1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "reinforced-chests-2.4.4+1.20.jar",
          "url": "reinforced-chests-2.4.4+1.20.jar",
          "size": 1128790,
          "sha512": "9d705ff1be8fa5e296d5da2100269fe8c5b4edb95a7add31acb9eb2cc9500fa7190f3a9e5affe7db59b1539dbfcc92887e18474189839304b77da70d994a3868",
          "sha256": "4f91ddec1c81f475b1361b0004cf385a8a6b7a419f233c1920263c554a47f1f7",
          "sha1": "dc456fb4ddf9016f3ce1c18ba577dd725f58b12f",
          "md5": "6b3edd875130fb5577b4419150874548"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.91.1+1.20.4"
          }
        },
        {
          "group": "atonkish.reinfcore",
          "module": "reinforced-core",
          "version": {
            "requires": "3.1.3+1.20"
          }
        }
      ],
      "files": [
        {
          "name": "reinforced-chests-2.4.4+1.20.jar",
          "url": "reinforced-chests-2.4.4+1.20.jar",
          "size": 1128790,
          "sha512": "9d705ff1be8fa5e296d5da2100269fe8c5b4edb95a7add31acb9eb2cc9500fa7190f3a9e5affe7db59b1539dbfcc92887e18474189839304b77da70d994a3868",
          "sha256": "4f91ddec1c81f475b1361b0004cf385a8a6b7a419f233c1920263c554a47f1f7",
          "sha1": "dc456fb4ddf9016f3ce1c18ba577dd725f58b12f",
          "md5": "6b3edd875130fb5577b4419150874548"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
