{
  "formatVersion": "1.1",
  "component": {
    "group": "atonkish.reinfshulker",
    "module": "reinforced-shulker-boxes",
    "version": "2.2.0+1.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "reinforced-shulker-boxes-2.2.0+1.17.jar",
          "url": "reinforced-shulker-boxes-2.2.0+1.17.jar",
          "size": 1403598,
          "sha512": "c162fc6aee0ebf92b25322dc53fe954ee6d487cc4329d67b163f430856023166fa23a195c27c6de62216d9d9f8b21f62e5f4bd492d5d5510f60357f919453526",
          "sha256": "4658f3abc9f9f199bd2152c18c2cc2faca1bf21018966ae3dae75ce04c8a668b",
          "sha1": "aaae47eab34dce4437775647909363b8bb9310f2",
          "md5": "89e02c43ae3b6085fa7d3095a8b071f3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "blue.endless",
          "module": "jankson",
          "version": {
            "requires": "1.2.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.1+1.17"
          }
        },
        {
          "group": "atonkish.reinfcore",
          "module": "reinforced-core",
          "version": {
            "requires": "3.0.3+1.17"
          }
        },
        {
          "group": "atonkish.reinfchest",
          "module": "reinforced-chests",
          "version": {
            "requires": "2.2.0+1.17"
          }
        },
        {
          "group": "net.kyrptonaught",
          "module": "quickshulker",
          "version": {
            "requires": "1.3.0-1.17"
          }
        },
        {
          "group": "com.misterpemodder",
          "module": "shulkerboxtooltip",
          "version": {
            "requires": "3.0.6+1.17.1"
          }
        }
      ],
      "files": [
        {
          "name": "reinforced-shulker-boxes-2.2.0+1.17.jar",
          "url": "reinforced-shulker-boxes-2.2.0+1.17.jar",
          "size": 1403598,
          "sha512": "c162fc6aee0ebf92b25322dc53fe954ee6d487cc4329d67b163f430856023166fa23a195c27c6de62216d9d9f8b21f62e5f4bd492d5d5510f60357f919453526",
          "sha256": "4658f3abc9f9f199bd2152c18c2cc2faca1bf21018966ae3dae75ce04c8a668b",
          "sha1": "aaae47eab34dce4437775647909363b8bb9310f2",
          "md5": "89e02c43ae3b6085fa7d3095a8b071f3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "reinforced-shulker-boxes-2.2.0+1.17-sources.jar",
          "url": "reinforced-shulker-boxes-2.2.0+1.17-sources.jar",
          "size": 382235,
          "sha512": "4484df68c4ddc51f1d81617825343d33810b79dba98a5b65c1b5f324b53802c4d8ba6e3f2eb418b1bba001838f483f54f28dd075dc0d14b1ed615686fbe78e5f",
          "sha256": "992adae04d2b6e53b9302d22275ea3439e02485dcfb202d1320ba38031e16039",
          "sha1": "9a600fe50498c2e69fbfa78f35fd9298f515e939",
          "md5": "f10c2d7e5985631eb2aa36ad3ba84e96"
        }
      ]
    }
  ]
}
