{
  "formatVersion": "1.1",
  "component": {
    "group": "atonkish.reinfshulker",
    "module": "reinforced-shulker-boxes",
    "version": "3.0.0+1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "reinforced-shulker-boxes-3.0.0+1.20.jar",
          "url": "reinforced-shulker-boxes-3.0.0+1.20.jar",
          "size": 1476889,
          "sha512": "01b6c4d82cd62d6851022af258f270c40433e77e1c21de4cac92c4d6b95957fdcd3d4fc0f20d980fd529c50284333dbf09cb11e7a8f921ade7d4858f8abe131c",
          "sha256": "b31e3fcc247fb3120a5e11742dfc0823bcd3859975947f6165c2388767d6656d",
          "sha1": "4d949488cca765cb93ff02fc2625ec9a3d7bc2bc",
          "md5": "277ffa3dff8d8cd80f5da8c16968105e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.100.0+1.20.6"
          }
        },
        {
          "group": "atonkish.reinfcore",
          "module": "reinforced-core",
          "version": {
            "requires": "4.0.0+1.20"
          }
        },
        {
          "group": "atonkish.reinfchest",
          "module": "reinforced-chests",
          "version": {
            "requires": "3.0.0+1.20"
          }
        },
        {
          "group": "com.misterpemodder",
          "module": "shulkerboxtooltip-fabric",
          "version": {
            "requires": "4.1.0-alpha.4+1.20.6"
          }
        }
      ],
      "files": [
        {
          "name": "reinforced-shulker-boxes-3.0.0+1.20.jar",
          "url": "reinforced-shulker-boxes-3.0.0+1.20.jar",
          "size": 1476889,
          "sha512": "01b6c4d82cd62d6851022af258f270c40433e77e1c21de4cac92c4d6b95957fdcd3d4fc0f20d980fd529c50284333dbf09cb11e7a8f921ade7d4858f8abe131c",
          "sha256": "b31e3fcc247fb3120a5e11742dfc0823bcd3859975947f6165c2388767d6656d",
          "sha1": "4d949488cca765cb93ff02fc2625ec9a3d7bc2bc",
          "md5": "277ffa3dff8d8cd80f5da8c16968105e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "reinforced-shulker-boxes-3.0.0+1.20-sources.jar",
          "url": "reinforced-shulker-boxes-3.0.0+1.20-sources.jar",
          "size": 394359,
          "sha512": "a73fcf9c20ee2c047f9b1621b125613d680db880b5bbc69bd5efa6692ffa6ee35ca9095412fea917b79ad579dc99c891fd93c06ac2e1cc50d672aa7455929597",
          "sha256": "faced054713a801ae6f80c012fa3c5e484d29f16387055120606dc76f931ceca",
          "sha1": "ea8db4634d1132e342ad26d1c17a9f83cd0392b5",
          "md5": "2ab73ddbc10eb4bb205cbe4cfad75e7b"
        }
      ]
    }
  ]
}
