{
  "formatVersion": "1.1",
  "component": {
    "group": "atonkish.reinfcore",
    "module": "reinforced-core",
    "version": "3.0.0+1.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "blue.endless",
          "module": "jankson",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.27"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "8.0.75"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "reinforced-core-3.0.0+1.19.jar",
          "url": "reinforced-core-3.0.0+1.19.jar",
          "size": 41064,
          "sha512": "fdfc171bce86cb6ebf1ed64aacffa140cd1f7d122fe1aeafb94bbbf8c1db4356be3d23a55d03958bdd0ea6752fe01f3cf4cc15154f341db5a68ee07475402b61",
          "sha256": "35b934e05d680c9b460985c57c003e2bc26607fdecf585783cf0fe038806351f",
          "sha1": "1e96ca9d4f9a4c23b437a06c35f1f7af50059425",
          "md5": "bc3fa91b744a82396873517ea79971a4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "blue.endless",
          "module": "jankson",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.27"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "8.0.75"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.59.0+1.19.2"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "4.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "reinforced-core-3.0.0+1.19.jar",
          "url": "reinforced-core-3.0.0+1.19.jar",
          "size": 41064,
          "sha512": "fdfc171bce86cb6ebf1ed64aacffa140cd1f7d122fe1aeafb94bbbf8c1db4356be3d23a55d03958bdd0ea6752fe01f3cf4cc15154f341db5a68ee07475402b61",
          "sha256": "35b934e05d680c9b460985c57c003e2bc26607fdecf585783cf0fe038806351f",
          "sha1": "1e96ca9d4f9a4c23b437a06c35f1f7af50059425",
          "md5": "bc3fa91b744a82396873517ea79971a4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "reinforced-core-3.0.0+1.19-sources.jar",
          "url": "reinforced-core-3.0.0+1.19-sources.jar",
          "size": 27870,
          "sha512": "540233ba7007fc6ed697b197be0a00d7e3e101f827c9380146fc4fb82ebadf9154daed57ffe460139f9bb4f91be42063eb667bcef3870d67054311d15006bc9b",
          "sha256": "f30eae4da837112886dd1dce926f14d21941538807fe8e8886b7e3248c81ed9e",
          "sha1": "a3d036d22524a508ae33b006560a0ef0ccf2e004",
          "md5": "3296ee82cb07b9b2da8bc2e10ea39f90"
        }
      ]
    }
  ]
}
