{
  "formatVersion": "1.1",
  "component": {
    "group": "atonkish.reinfshulker",
    "module": "reinforced-shulker-boxes",
    "version": "1.1.7+1.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "reinforced-shulker-boxes-1.1.7+1.17.jar",
          "url": "reinforced-shulker-boxes-1.1.7+1.17.jar",
          "size": 426261,
          "sha512": "899a9deb17aaee31c50b2283029333ae454cef8126a8791a721c7cd6af87241c18c25f5c965f8547c6ea68f2c74ea67ac84f29f701530401a9cbedd9530dfc95",
          "sha256": "88095349753eef5f8fce4d49d6c09952638d3f8c9170dbf22a984e3d5a3a4d50",
          "sha1": "4a14bccfbaa9f8dc221fd2bb98261f2006d7dcc4",
          "md5": "5a09479df78e16e30aba706cdb96462c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "blue.endless",
          "module": "jankson",
          "version": {
            "requires": "1.2.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.12.12"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.45.0+1.17"
          }
        },
        {
          "group": "atonkish.reinfcore",
          "module": "reinforced-core",
          "version": {
            "requires": "1.1.1+1.17"
          }
        },
        {
          "group": "net.kyrptonaught",
          "module": "quickshulker",
          "version": {
            "requires": "1.3.0-1.17"
          }
        },
        {
          "group": "com.misterpemodder",
          "module": "shulkerboxtooltip",
          "version": {
            "requires": "3.0.4+1.17.1"
          }
        }
      ],
      "files": [
        {
          "name": "reinforced-shulker-boxes-1.1.7+1.17.jar",
          "url": "reinforced-shulker-boxes-1.1.7+1.17.jar",
          "size": 426261,
          "sha512": "899a9deb17aaee31c50b2283029333ae454cef8126a8791a721c7cd6af87241c18c25f5c965f8547c6ea68f2c74ea67ac84f29f701530401a9cbedd9530dfc95",
          "sha256": "88095349753eef5f8fce4d49d6c09952638d3f8c9170dbf22a984e3d5a3a4d50",
          "sha1": "4a14bccfbaa9f8dc221fd2bb98261f2006d7dcc4",
          "md5": "5a09479df78e16e30aba706cdb96462c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "reinforced-shulker-boxes-1.1.7+1.17-sources.jar",
          "url": "reinforced-shulker-boxes-1.1.7+1.17-sources.jar",
          "size": 373827,
          "sha512": "2c9e97a055d827567ae831d75609f0b6df617ef93cbec3361165c033a6e8a7f00b79fdc8d7dbd3a5f70595146e00769ed2c11f3e695a7c39e300d9bd19863580",
          "sha256": "1486914b04e11ec72908ca31629255a0b6ee4fc16ebbf64d3ef8530b26683621",
          "sha1": "6abc95c32029b6788c6881e5553d1aeaa8455d81",
          "md5": "82595220b5bd8b146c9b8988eeed08b3"
        }
      ]
    }
  ]
}
