{
  "formatVersion": "1.1",
  "component": {
    "group": "atonkish.reinfshulker",
    "module": "reinforced-shulker-boxes",
    "version": "2.3.1+1.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "reinforced-shulker-boxes-2.3.1+1.19.jar",
          "url": "reinforced-shulker-boxes-2.3.1+1.19.jar",
          "size": 1444290,
          "sha512": "6eda9c9122000c1559afa6dde1b12e4658cf0ccecfd3a8e82daf646808caa24762ad30ee7d10af432c967f143fc80c6e0e9332f924cd47842d8b67ef9e763eef",
          "sha256": "f5cbdba8005a28d5b3955f00eb6bd37be1e47af50e469af7a84f93ef7db9c520",
          "sha1": "fc5f8f75699b5fa5b8cc595981ef67db4e5af124",
          "md5": "b8ff20f0b7f0240444476a3274435e7c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "blue.endless",
          "module": "jankson",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.27"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.14"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.74.0+1.19.3"
          }
        },
        {
          "group": "atonkish.reinfcore",
          "module": "reinforced-core",
          "version": {
            "requires": "3.0.5+1.19"
          }
        },
        {
          "group": "atonkish.reinfchest",
          "module": "reinforced-chests",
          "version": {
            "requires": "2.3.1+1.19"
          }
        },
        {
          "group": "net.kyrptonaught",
          "module": "quickshulker",
          "version": {
            "requires": "1.3.10-1.19.3"
          }
        },
        {
          "group": "com.misterpemodder",
          "module": "shulkerboxtooltip-fabric",
          "version": {
            "requires": "3.2.4+1.19.3"
          }
        }
      ],
      "files": [
        {
          "name": "reinforced-shulker-boxes-2.3.1+1.19.jar",
          "url": "reinforced-shulker-boxes-2.3.1+1.19.jar",
          "size": 1444290,
          "sha512": "6eda9c9122000c1559afa6dde1b12e4658cf0ccecfd3a8e82daf646808caa24762ad30ee7d10af432c967f143fc80c6e0e9332f924cd47842d8b67ef9e763eef",
          "sha256": "f5cbdba8005a28d5b3955f00eb6bd37be1e47af50e469af7a84f93ef7db9c520",
          "sha1": "fc5f8f75699b5fa5b8cc595981ef67db4e5af124",
          "md5": "b8ff20f0b7f0240444476a3274435e7c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "reinforced-shulker-boxes-2.3.1+1.19-sources.jar",
          "url": "reinforced-shulker-boxes-2.3.1+1.19-sources.jar",
          "size": 383515,
          "sha512": "bc472ab22f6c7064ddc8f88be8c3a470d7b3d93db30321712239d59bd12acf6cefc5978fee510ef1f5f2c99361f1f802d5a35bbc3c7e48c854dc39d1ddab602a",
          "sha256": "19b9804af40a00f0e133c84a738cd4058eb6cbf276f455c8af5d1ab651d1d454",
          "sha1": "2c52d7bfe00b734c850931a73071afbd38b175c5",
          "md5": "cb3204ecc9bf2d020251b25d4d2aac89"
        }
      ]
    }
  ]
}
