{
  "formatVersion": "1.1",
  "component": {
    "group": "atonkish.reinfshulker",
    "module": "reinforced-shulker-boxes",
    "version": "2.0.3+1.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "reinforced-shulker-boxes-2.0.3+1.19.jar",
          "url": "reinforced-shulker-boxes-2.0.3+1.19.jar",
          "size": 436485,
          "sha512": "a15060d6fbad2ee5c6c2c751857b16a1f2c453adb1da1b8bb3c8caeda68b28dac5668f883406c18b4baac3f48c03b12e88ded4062c343992afc293168d6c1866",
          "sha256": "fb71481dc8775a354982b2edf127af8b499124226705a2e4967438e6b25dab13",
          "sha1": "ce65230bd8842195d26073f8c54d529a91bf2b17",
          "md5": "439f10dec9208fd2006d919a2a9c90b8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "blue.endless",
          "module": "jankson",
          "version": {
            "requires": "1.2.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.27"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.8"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.57.0+1.19"
          }
        },
        {
          "group": "atonkish.reinfcore",
          "module": "reinforced-core",
          "version": {
            "requires": "2.1.0+1.19"
          }
        },
        {
          "group": "atonkish.reinfchest",
          "module": "reinforced-chests",
          "version": {
            "requires": "2.0.3+1.19"
          }
        },
        {
          "group": "net.kyrptonaught",
          "module": "quickshulker",
          "version": {
            "requires": "1.3.6-1.19"
          }
        },
        {
          "group": "com.misterpemodder",
          "module": "shulkerboxtooltip",
          "version": {
            "requires": "3.0.10+1.19"
          }
        }
      ],
      "files": [
        {
          "name": "reinforced-shulker-boxes-2.0.3+1.19.jar",
          "url": "reinforced-shulker-boxes-2.0.3+1.19.jar",
          "size": 436485,
          "sha512": "a15060d6fbad2ee5c6c2c751857b16a1f2c453adb1da1b8bb3c8caeda68b28dac5668f883406c18b4baac3f48c03b12e88ded4062c343992afc293168d6c1866",
          "sha256": "fb71481dc8775a354982b2edf127af8b499124226705a2e4967438e6b25dab13",
          "sha1": "ce65230bd8842195d26073f8c54d529a91bf2b17",
          "md5": "439f10dec9208fd2006d919a2a9c90b8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "reinforced-shulker-boxes-2.0.3+1.19-sources.jar",
          "url": "reinforced-shulker-boxes-2.0.3+1.19-sources.jar",
          "size": 379085,
          "sha512": "a52953c026355d8aa9047f67a96d8c62efacc9c886d2e875db9a8f3eb6082f20c197873ab0e7c3c00510b7fb33874f90b268c0954f575b6cabde1991a91225f1",
          "sha256": "26aa53e822895905a2bc9f0ec27d028a68951290f6035a28a4989d9993c9f9d7",
          "sha1": "c6cbdde434666a6c665ccff1588aa76563e2cba5",
          "md5": "7f5708c20caf1abde049abedcf074e39"
        }
      ]
    }
  ]
}
