{
  "formatVersion": "1.1",
  "component": {
    "group": "atonkish.reinfshulker",
    "module": "reinforced-shulker-boxes",
    "version": "2.5.2+1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "reinforced-shulker-boxes-2.5.2+1.20.jar",
          "url": "reinforced-shulker-boxes-2.5.2+1.20.jar",
          "size": 1436218,
          "sha512": "c4851bc86b72829516df9185086c046faa97e69fac908f78acf7d1a6ca0742a1185e170cdae876528b970245d93fa30e9412fc88777c211a56c807aa1499c9c1",
          "sha256": "7f94ad40dde84768eb358832d7a69ec3216db532c4cd197682204d44fa4f01d9",
          "sha1": "2ad0f7991663a6aedb39849bb5ec9cc9e539fcbe",
          "md5": "7c7bdaaa0e27bb39b51e9274690a3f98"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.91.1+1.20.4"
          }
        },
        {
          "group": "atonkish.reinfcore",
          "module": "reinforced-core",
          "version": {
            "requires": "3.1.3+1.20"
          }
        },
        {
          "group": "atonkish.reinfchest",
          "module": "reinforced-chests",
          "version": {
            "requires": "2.4.3+1.20"
          }
        },
        {
          "group": "net.kyrptonaught",
          "module": "quickshulker",
          "version": {
            "requires": "1.4.0-1.20"
          }
        },
        {
          "group": "net.kyrptonaught",
          "module": "shulkerutils",
          "version": {
            "requires": "1.0.4-1.19"
          }
        },
        {
          "group": "com.misterpemodder",
          "module": "shulkerboxtooltip-fabric",
          "version": {
            "requires": "4.0.7+1.20.2"
          }
        }
      ],
      "files": [
        {
          "name": "reinforced-shulker-boxes-2.5.2+1.20.jar",
          "url": "reinforced-shulker-boxes-2.5.2+1.20.jar",
          "size": 1436218,
          "sha512": "c4851bc86b72829516df9185086c046faa97e69fac908f78acf7d1a6ca0742a1185e170cdae876528b970245d93fa30e9412fc88777c211a56c807aa1499c9c1",
          "sha256": "7f94ad40dde84768eb358832d7a69ec3216db532c4cd197682204d44fa4f01d9",
          "sha1": "2ad0f7991663a6aedb39849bb5ec9cc9e539fcbe",
          "md5": "7c7bdaaa0e27bb39b51e9274690a3f98"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
