{
  "formatVersion": "1.1",
  "component": {
    "group": "atonkish.reinfshulker",
    "module": "reinforced-shulker-boxes",
    "version": "1.1.4+1.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "reinforced-shulker-boxes-1.1.4+1.18.jar",
          "url": "reinforced-shulker-boxes-1.1.4+1.18.jar",
          "size": 425062,
          "sha512": "6efcee9b584168b53d928bd4114894d18d673ca7ecb7e15325782733147ad830ddefb1c255d03afc7b83ab5bb9c08494eab9c3878c01969352ed781b31917791",
          "sha256": "0c35594644c9e53f04bf952b8cc3a6ea288f9a08a422c64ede92fb1280aca853",
          "sha1": "c8b6a4920c9b585c51bc1086302ba4cf83dbd135",
          "md5": "8b85927135b28b28df4716cfdfd78347"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "blue.endless",
          "module": "jankson",
          "version": {
            "requires": "1.2.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.12.8"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.43.1+1.18"
          }
        },
        {
          "group": "atonkish.reinfcore",
          "module": "reinforced-core",
          "version": {
            "requires": "1.1.2+1.18"
          }
        },
        {
          "group": "net.kyrptonaught",
          "module": "quickshulker",
          "version": {
            "requires": "1.3.1-1.18"
          }
        },
        {
          "group": "com.misterpemodder",
          "module": "shulkerboxtooltip",
          "version": {
            "requires": "3.0.5-beta.1+1.18-pre5"
          }
        }
      ],
      "files": [
        {
          "name": "reinforced-shulker-boxes-1.1.4+1.18.jar",
          "url": "reinforced-shulker-boxes-1.1.4+1.18.jar",
          "size": 425062,
          "sha512": "6efcee9b584168b53d928bd4114894d18d673ca7ecb7e15325782733147ad830ddefb1c255d03afc7b83ab5bb9c08494eab9c3878c01969352ed781b31917791",
          "sha256": "0c35594644c9e53f04bf952b8cc3a6ea288f9a08a422c64ede92fb1280aca853",
          "sha1": "c8b6a4920c9b585c51bc1086302ba4cf83dbd135",
          "md5": "8b85927135b28b28df4716cfdfd78347"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "reinforced-shulker-boxes-1.1.4+1.18-sources.jar",
          "url": "reinforced-shulker-boxes-1.1.4+1.18-sources.jar",
          "size": 373354,
          "sha512": "c53a2d49548fd622d9b3844000c726b3b998ce69548e71d97f83d21939f0801715aec5202f7af0b61afc7789f702f07fc989d3d8e99b96fb26efc85656216294",
          "sha256": "9e3e2c9fb2b2ba2290ae3977430aebf8e0487b03f093d8d14e1a59f3788562d1",
          "sha1": "ae90e5f3ee753d14d2c1a9136854573b8e6f0beb",
          "md5": "11d250d95b520af71fb0468e77d33173"
        }
      ]
    }
  ]
}
