{
  "formatVersion": "1.1",
  "component": {
    "group": "atonkish.enderitestorage",
    "module": "enderite-reinforced-storage",
    "version": "1.0.2+1.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "enderite-reinforced-storage-1.0.2+1.19.jar",
          "url": "enderite-reinforced-storage-1.0.2+1.19.jar",
          "size": 123739,
          "sha512": "444332c8c3731141eaeb6b31c1f2748bdd4d2a912da44bbe457ab942f2cb209304890f2c28ba75a075cfdf072909d1ea7a05b2dac38bb4486e1877e5fca532db",
          "sha256": "9c16803f5cb2a1297bc524486827f4fe39627fb56ef890706f46c3be541b4954",
          "sha1": "790777714d013f0ca07287dd504e1613a19c946a",
          "md5": "4ea6e36507b734ca382beb03379094dc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "blue.endless",
          "module": "jankson",
          "version": {
            "requires": "1.2.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.27"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.8"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.56.0+1.19"
          }
        },
        {
          "group": "curse.maven",
          "module": "enderite-mod-for-fabric-399221",
          "version": {
            "requires": "3826746"
          }
        },
        {
          "group": "atonkish.reinfchest",
          "module": "reinforced-chests",
          "version": {
            "requires": "2.0.2+1.19"
          }
        },
        {
          "group": "atonkish.reinfshulker",
          "module": "reinforced-shulker-boxes",
          "version": {
            "requires": "2.0.2+1.19"
          }
        },
        {
          "group": "atonkish.reinfbarrel",
          "module": "reinforced-barrels",
          "version": {
            "requires": "2.0.2+1.19"
          }
        }
      ],
      "files": [
        {
          "name": "enderite-reinforced-storage-1.0.2+1.19.jar",
          "url": "enderite-reinforced-storage-1.0.2+1.19.jar",
          "size": 123739,
          "sha512": "444332c8c3731141eaeb6b31c1f2748bdd4d2a912da44bbe457ab942f2cb209304890f2c28ba75a075cfdf072909d1ea7a05b2dac38bb4486e1877e5fca532db",
          "sha256": "9c16803f5cb2a1297bc524486827f4fe39627fb56ef890706f46c3be541b4954",
          "sha1": "790777714d013f0ca07287dd504e1613a19c946a",
          "md5": "4ea6e36507b734ca382beb03379094dc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "enderite-reinforced-storage-1.0.2+1.19-sources.jar",
          "url": "enderite-reinforced-storage-1.0.2+1.19-sources.jar",
          "size": 112944,
          "sha512": "ccf9acd19158b042a6a3a8b1860a90f9a63f542e2dc4dc48c4a2c4d64dc8349245ca876e89d3257836b97fc5ff4ab0f87b983e218d53ef200fe4306aa9f8357d",
          "sha256": "1f5477e99d4b566e52a5a7221cb2e0e4af46e0b812f273252cd0a76217e9c170",
          "sha1": "24cb19dbed55af1a74726e49c515536161c5a146",
          "md5": "b4b9f01d447534e2279828e8f2a95232"
        }
      ]
    }
  ]
}
