{
  "formatVersion": "1.1",
  "component": {
    "group": "atonkish.reinfchest",
    "module": "reinforced-chests",
    "version": "2.4.3+1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "reinforced-chests-2.4.3+1.20.jar",
          "url": "reinforced-chests-2.4.3+1.20.jar",
          "size": 1128790,
          "sha512": "7e8eb72f68159872e4aacdc36fa84953c215d62f778f9df24f4e946b2cf12ba3efbdeb421d4f6fe764f8fa01f64d6d17096b99ec93b9002cc4f6ba9727894543",
          "sha256": "42193b07d1a75c01bc253d8f91c412d6780f496a86114ef12a55292de2abbee0",
          "sha1": "13edbae0d5888008c6a0159d45904e6f2773948a",
          "md5": "f0749f820023609e41258e85e43c7dbf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.91.2+1.20.2"
          }
        },
        {
          "group": "atonkish.reinfcore",
          "module": "reinforced-core",
          "version": {
            "requires": "3.1.3+1.20"
          }
        }
      ],
      "files": [
        {
          "name": "reinforced-chests-2.4.3+1.20.jar",
          "url": "reinforced-chests-2.4.3+1.20.jar",
          "size": 1128790,
          "sha512": "7e8eb72f68159872e4aacdc36fa84953c215d62f778f9df24f4e946b2cf12ba3efbdeb421d4f6fe764f8fa01f64d6d17096b99ec93b9002cc4f6ba9727894543",
          "sha256": "42193b07d1a75c01bc253d8f91c412d6780f496a86114ef12a55292de2abbee0",
          "sha1": "13edbae0d5888008c6a0159d45904e6f2773948a",
          "md5": "f0749f820023609e41258e85e43c7dbf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
