{
  "formatVersion": "1.1",
  "component": {
    "group": "atonkish.reinfcore",
    "module": "reinforced-core",
    "version": "4.0.2+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "15.0.130"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "reinforced-core-4.0.2+1.21.1.jar",
          "url": "reinforced-core-4.0.2+1.21.1.jar",
          "size": 1045442,
          "sha512": "2ec21821ee1508d1f0ea74de117824dfc7d30b5714d91eea099a7fac5fdde6d3c9e6dbe79d4a218421f658bd9ef074d78459543002674b7a6711eb9cea09ce8a",
          "sha256": "2c1d3add050fda1f85cc530f4fb717ac6bbb5f9ed4b54744f762a5b0f2d2d834",
          "sha1": "d9355e02e2ba04e3fa66586bbd467cb354ff6223",
          "md5": "43ebec2de668610667cce9d58819412c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "15.0.130"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.103.0+1.21.1"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "11.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "reinforced-core-4.0.2+1.21.1.jar",
          "url": "reinforced-core-4.0.2+1.21.1.jar",
          "size": 1045442,
          "sha512": "2ec21821ee1508d1f0ea74de117824dfc7d30b5714d91eea099a7fac5fdde6d3c9e6dbe79d4a218421f658bd9ef074d78459543002674b7a6711eb9cea09ce8a",
          "sha256": "2c1d3add050fda1f85cc530f4fb717ac6bbb5f9ed4b54744f762a5b0f2d2d834",
          "sha1": "d9355e02e2ba04e3fa66586bbd467cb354ff6223",
          "md5": "43ebec2de668610667cce9d58819412c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "reinforced-core-4.0.2+1.21.1-sources.jar",
          "url": "reinforced-core-4.0.2+1.21.1-sources.jar",
          "size": 29865,
          "sha512": "862d64dadc72148131813d4b36485844b4a748ed5d7d853fd10f170e3b1b18f6f48b088ce04770cd52726946b752e1189c2e6f264fd7e5a19044b228c51d5366",
          "sha256": "691d36b31be00db26ad9ffd278108ae7fb4e2c63ee7b6de5d16998759df01265",
          "sha1": "ad5806ba7ac80ec3ebdeaa8503430ac1106457c9",
          "md5": "141503609661ebbbae184f2c2219f5e9"
        }
      ]
    }
  ]
}
