{
  "formatVersion": "1.1",
  "component": {
    "group": "atonkish.reinfshulker",
    "module": "reinforced-shulker-boxes",
    "version": "2.0.4+1.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "reinforced-shulker-boxes-2.0.4+1.19.jar",
          "url": "reinforced-shulker-boxes-2.0.4+1.19.jar",
          "size": 436980,
          "sha512": "f5dc54d3ceb6ae463e5c62298cffb76155fc07fd0ae226d129434b81c294690197b0358b094b600b290ba27513619243ec4fc45d8b68236d920179cf617a181e",
          "sha256": "e55396018e841adf20051199de9801c10c6aedbb7609fd6b7d85526b4141255f",
          "sha1": "c78c4e9275cfcc2aaaec0815ce94f446a6a76b4b",
          "md5": "272fa8ecee25cc1ca6149ddbfe0c90db"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "blue.endless",
          "module": "jankson",
          "version": {
            "requires": "1.2.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.27"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.8"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.58.5+1.19.1"
          }
        },
        {
          "group": "atonkish.reinfcore",
          "module": "reinforced-core",
          "version": {
            "requires": "2.1.1+1.19"
          }
        },
        {
          "group": "atonkish.reinfchest",
          "module": "reinforced-chests",
          "version": {
            "requires": "2.0.4+1.19"
          }
        },
        {
          "group": "net.kyrptonaught",
          "module": "quickshulker",
          "version": {
            "requires": "1.3.6-1.19"
          }
        },
        {
          "group": "com.misterpemodder",
          "module": "shulkerboxtooltip",
          "version": {
            "requires": "3.0.10+1.19"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "4.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "reinforced-shulker-boxes-2.0.4+1.19.jar",
          "url": "reinforced-shulker-boxes-2.0.4+1.19.jar",
          "size": 436980,
          "sha512": "f5dc54d3ceb6ae463e5c62298cffb76155fc07fd0ae226d129434b81c294690197b0358b094b600b290ba27513619243ec4fc45d8b68236d920179cf617a181e",
          "sha256": "e55396018e841adf20051199de9801c10c6aedbb7609fd6b7d85526b4141255f",
          "sha1": "c78c4e9275cfcc2aaaec0815ce94f446a6a76b4b",
          "md5": "272fa8ecee25cc1ca6149ddbfe0c90db"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "reinforced-shulker-boxes-2.0.4+1.19-sources.jar",
          "url": "reinforced-shulker-boxes-2.0.4+1.19-sources.jar",
          "size": 379204,
          "sha512": "295d9407b42ab5408513798d219d5c4166f325dad8f8df57c6d9ff8e2b6ce2fd4a9764c3021aa9b2711c546a97ca9f61ba47c588e3576ab2a2628d2e2eae42b5",
          "sha256": "35df4e19bb2631dce3fa559ce03df6de70a7c16dd5d799a2e1cbc54314126c6a",
          "sha1": "5108a18695e7d1ad3b27acbc2c59b4e932de8a91",
          "md5": "5d7f303b62f9d38c2a13b39de803d9bd"
        }
      ]
    }
  ]
}
