{
  "formatVersion": "1.1",
  "component": {
    "group": "atonkish.reinfshulker",
    "module": "reinforced-shulker-boxes",
    "version": "2.3.2+1.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "reinforced-shulker-boxes-2.3.2+1.19.jar",
          "url": "reinforced-shulker-boxes-2.3.2+1.19.jar",
          "size": 1449294,
          "sha512": "746242bac7cab5be36562715d94f612e88dc369c9db0c3dcc11c41ff41e4864c6412a0108e78269f4f8d13682083e1db33c216e9a51848065bf784be7a493726",
          "sha256": "7f4dd5275c575dff7839104cbfcf7bd18296b6c21ddac7796b9dfc560a8408e8",
          "sha1": "a3f8c438edd95cff2668c679ae1609904bc830de",
          "md5": "25c743dbc7780938bdadb06c39645010"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.17"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.19.4"
          }
        },
        {
          "group": "atonkish.reinfcore",
          "module": "reinforced-core",
          "version": {
            "requires": "3.0.6+1.19"
          }
        },
        {
          "group": "atonkish.reinfchest",
          "module": "reinforced-chests",
          "version": {
            "requires": "2.3.2+1.19"
          }
        },
        {
          "group": "net.kyrptonaught",
          "module": "quickshulker",
          "version": {
            "requires": "1.3.10-1.19.4"
          }
        },
        {
          "group": "net.kyrptonaught",
          "module": "shulkerutils",
          "version": {
            "requires": "1.0.4-1.19"
          }
        },
        {
          "group": "com.misterpemodder",
          "module": "shulkerboxtooltip-fabric",
          "version": {
            "requires": "3.2.5+1.19.4"
          }
        }
      ],
      "files": [
        {
          "name": "reinforced-shulker-boxes-2.3.2+1.19.jar",
          "url": "reinforced-shulker-boxes-2.3.2+1.19.jar",
          "size": 1449294,
          "sha512": "746242bac7cab5be36562715d94f612e88dc369c9db0c3dcc11c41ff41e4864c6412a0108e78269f4f8d13682083e1db33c216e9a51848065bf784be7a493726",
          "sha256": "7f4dd5275c575dff7839104cbfcf7bd18296b6c21ddac7796b9dfc560a8408e8",
          "sha1": "a3f8c438edd95cff2668c679ae1609904bc830de",
          "md5": "25c743dbc7780938bdadb06c39645010"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "reinforced-shulker-boxes-2.3.2+1.19-sources.jar",
          "url": "reinforced-shulker-boxes-2.3.2+1.19-sources.jar",
          "size": 383691,
          "sha512": "83108c80ace3da007691f5b391c4746c5a7ad61b9c16046788514bb674b57e2a9f3f887886743ce51eea463a8a57bca17311a265003428561f06c863d94df84a",
          "sha256": "2f23c614f47792306433d8b7d0061e101e40206b958d1c93d61f286e652ca36d",
          "sha1": "952aae017ddc3937652fdd307d191ce2cb6e0526",
          "md5": "380958f00154153d2673b1df7992431c"
        }
      ]
    }
  ]
}
