{
  "formatVersion": "1.1",
  "component": {
    "group": "atonkish.reinfshulker",
    "module": "reinforced-shulker-boxes",
    "version": "1.1.6+1.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "reinforced-shulker-boxes-1.1.6+1.17.jar",
          "url": "reinforced-shulker-boxes-1.1.6+1.17.jar",
          "size": 426115,
          "sha512": "46bce35df21db29d2e81e7ee39f9d68fc24d43cea2e9dfbf135f89380145d76330527c1206547351bdb7d099064c8999a29e5c6646be002cd0b1752c71e83c20",
          "sha256": "68b3dbf717be91a57c2f76b3843bc817bd59270015a4b90671ef82f53c843958",
          "sha1": "ae6bb77fce9c009fbe73f07a1decbdf9ca28a92c",
          "md5": "8347665728b5f196375540514da77f53"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "blue.endless",
          "module": "jankson",
          "version": {
            "requires": "1.2.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.12.12"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.45.0+1.17"
          }
        },
        {
          "group": "atonkish.reinfcore",
          "module": "reinforced-core",
          "version": {
            "requires": "1.1.1+1.17"
          }
        },
        {
          "group": "net.kyrptonaught",
          "module": "quickshulker",
          "version": {
            "requires": "1.3.0-1.17"
          }
        },
        {
          "group": "com.misterpemodder",
          "module": "shulkerboxtooltip",
          "version": {
            "requires": "3.0.4+1.17.1"
          }
        }
      ],
      "files": [
        {
          "name": "reinforced-shulker-boxes-1.1.6+1.17.jar",
          "url": "reinforced-shulker-boxes-1.1.6+1.17.jar",
          "size": 426115,
          "sha512": "46bce35df21db29d2e81e7ee39f9d68fc24d43cea2e9dfbf135f89380145d76330527c1206547351bdb7d099064c8999a29e5c6646be002cd0b1752c71e83c20",
          "sha256": "68b3dbf717be91a57c2f76b3843bc817bd59270015a4b90671ef82f53c843958",
          "sha1": "ae6bb77fce9c009fbe73f07a1decbdf9ca28a92c",
          "md5": "8347665728b5f196375540514da77f53"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "reinforced-shulker-boxes-1.1.6+1.17-sources.jar",
          "url": "reinforced-shulker-boxes-1.1.6+1.17-sources.jar",
          "size": 373760,
          "sha512": "bf3eb324e2931947a47efbde230860fd2a991c75de7d54a6d90a0811fb4a72a5b08e3571554a86ed0369ba4c7a249dedc62a138ffb7aeb828baa559a525a3dbb",
          "sha256": "b0bea0985c9e2074b73cd72e5282d928b61864198c83a5f73d35289ef7c34131",
          "sha1": "ca5aecbecfb725c18abbb3e9bc50310e0bee43b8",
          "md5": "079c05655faaa500c2008790f5d4fb2c"
        }
      ]
    }
  ]
}
