{
  "formatVersion": "1.1",
  "component": {
    "group": "atonkish.reinfshulker",
    "module": "reinforced-shulker-boxes",
    "version": "2.1.1+1.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "reinforced-shulker-boxes-2.1.1+1.17.jar",
          "url": "reinforced-shulker-boxes-2.1.1+1.17.jar",
          "size": 1401992,
          "sha512": "bf6f41b84aed340f5dc977311981b312bdc5fae4096adcc6145b8fafc252d393d8923019df08812c4ceabd45f349aa6b23f60d2f7f0a48fed139f1b7b72b0885",
          "sha256": "0f436346262fd1ef4934f64c3739bebd17030605bf4bc0b472cfbfe50fd4d377",
          "sha1": "eb9950447715332db78e55877d518618b9c30263",
          "md5": "3389c599213c168c0b711ee60c2369b3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "blue.endless",
          "module": "jankson",
          "version": {
            "requires": "1.2.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.1+1.17"
          }
        },
        {
          "group": "atonkish.reinfcore",
          "module": "reinforced-core",
          "version": {
            "requires": "3.0.2+1.17"
          }
        },
        {
          "group": "atonkish.reinfchest",
          "module": "reinforced-chests",
          "version": {
            "requires": "2.1.2+1.17"
          }
        },
        {
          "group": "net.kyrptonaught",
          "module": "quickshulker",
          "version": {
            "requires": "1.3.0-1.17"
          }
        },
        {
          "group": "com.misterpemodder",
          "module": "shulkerboxtooltip",
          "version": {
            "requires": "3.0.6+1.17.1"
          }
        }
      ],
      "files": [
        {
          "name": "reinforced-shulker-boxes-2.1.1+1.17.jar",
          "url": "reinforced-shulker-boxes-2.1.1+1.17.jar",
          "size": 1401992,
          "sha512": "bf6f41b84aed340f5dc977311981b312bdc5fae4096adcc6145b8fafc252d393d8923019df08812c4ceabd45f349aa6b23f60d2f7f0a48fed139f1b7b72b0885",
          "sha256": "0f436346262fd1ef4934f64c3739bebd17030605bf4bc0b472cfbfe50fd4d377",
          "sha1": "eb9950447715332db78e55877d518618b9c30263",
          "md5": "3389c599213c168c0b711ee60c2369b3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "reinforced-shulker-boxes-2.1.1+1.17-sources.jar",
          "url": "reinforced-shulker-boxes-2.1.1+1.17-sources.jar",
          "size": 380420,
          "sha512": "87d47bb22ae6124a95e35f1e50f361637ecafa992716ebf58c9361569433cfd1ebcf0f058bccd99a4eebca3fa6ab3134d8eea87eea6b42260769afd6394eb22c",
          "sha256": "e01dd91fc6f1b303fb0bd6473aedb6f8ea66a6e82d0e2739b1de4aacec8da609",
          "sha1": "7954b8989840173b895362cfd9b7402476538eea",
          "md5": "19932596dcc6a73d5420c4fb39a900c1"
        }
      ]
    }
  ]
}
