{
  "formatVersion": "1.1",
  "component": {
    "group": "atonkish.reinfshulker",
    "module": "reinforced-shulker-boxes",
    "version": "2.1.1+1.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "reinforced-shulker-boxes-2.1.1+1.19.jar",
          "url": "reinforced-shulker-boxes-2.1.1+1.19.jar",
          "size": 1426754,
          "sha512": "994a0076a39abbef9081319dd416da19458d7beff673a6fd866fd1315eb4c8b2083f30bf06e3a95c85585e820b69a2dab353483c3d655605376dba4bb40820ee",
          "sha256": "39e3bc1055e9eb2c641867b154ebac06be85d04160482d22089ee07df42624c8",
          "sha1": "33a421aab1d26f1d185168581af895cfc6cee90d",
          "md5": "80e6ba1c397d80f41086c82b252adf7c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "blue.endless",
          "module": "jankson",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.27"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.60.0+1.19.2"
          }
        },
        {
          "group": "atonkish.reinfcore",
          "module": "reinforced-core",
          "version": {
            "requires": "3.0.2+1.19"
          }
        },
        {
          "group": "atonkish.reinfchest",
          "module": "reinforced-chests",
          "version": {
            "requires": "2.1.2+1.19"
          }
        },
        {
          "group": "net.kyrptonaught",
          "module": "quickshulker",
          "version": {
            "requires": "1.3.7-1.19"
          }
        },
        {
          "group": "com.misterpemodder",
          "module": "shulkerboxtooltip",
          "version": {
            "requires": "3.0.10+1.19"
          }
        }
      ],
      "files": [
        {
          "name": "reinforced-shulker-boxes-2.1.1+1.19.jar",
          "url": "reinforced-shulker-boxes-2.1.1+1.19.jar",
          "size": 1426754,
          "sha512": "994a0076a39abbef9081319dd416da19458d7beff673a6fd866fd1315eb4c8b2083f30bf06e3a95c85585e820b69a2dab353483c3d655605376dba4bb40820ee",
          "sha256": "39e3bc1055e9eb2c641867b154ebac06be85d04160482d22089ee07df42624c8",
          "sha1": "33a421aab1d26f1d185168581af895cfc6cee90d",
          "md5": "80e6ba1c397d80f41086c82b252adf7c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "reinforced-shulker-boxes-2.1.1+1.19-sources.jar",
          "url": "reinforced-shulker-boxes-2.1.1+1.19-sources.jar",
          "size": 378863,
          "sha512": "0d756723bd12b12abe11aba12fb3a38e9c6ddd5a4bd304cf8fe02122e3482e01e79da0c337101b42468ed24c325e84008c1fb581a260ab5c966cc9ac8df6d9ed",
          "sha256": "516a42ff26003c537fd584da004aaa6a6336c5388f443096925683776fc03115",
          "sha1": "2a889ef575677278cab004e0d2457736a3613a91",
          "md5": "affd4c02d55edb783eba109c15fcfd1a"
        }
      ]
    }
  ]
}
