{
  "formatVersion": "1.1",
  "component": {
    "group": "atonkish.reinfbarrel",
    "module": "reinforced-barrels",
    "version": "2.5.0+1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "reinforced-barrels-2.5.0+1.20.jar",
          "url": "reinforced-barrels-2.5.0+1.20.jar",
          "size": 1128054,
          "sha512": "e163603bc4d1363708321e2ed724fe61b41ee9652e17b230b9d8703bf9100c2c3304a7c4e0fb0c33a0eabeaf1ec7c1d34e65a65d503ccbeea55e4e1ccbeb4a87",
          "sha256": "6ee9ec987d87c7877123748998633a3a8d186eb243213a39699e14c22eeaf3b0",
          "sha1": "4dd4011d7e810981d49765458362d532616b7961",
          "md5": "b0eddabdf355be7b2d078dccbda84f46"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.100.0+1.20.6"
          }
        },
        {
          "group": "atonkish.reinfcore",
          "module": "reinforced-core",
          "version": {
            "requires": "4.0.0+1.20"
          }
        }
      ],
      "files": [
        {
          "name": "reinforced-barrels-2.5.0+1.20.jar",
          "url": "reinforced-barrels-2.5.0+1.20.jar",
          "size": 1128054,
          "sha512": "e163603bc4d1363708321e2ed724fe61b41ee9652e17b230b9d8703bf9100c2c3304a7c4e0fb0c33a0eabeaf1ec7c1d34e65a65d503ccbeea55e4e1ccbeb4a87",
          "sha256": "6ee9ec987d87c7877123748998633a3a8d186eb243213a39699e14c22eeaf3b0",
          "sha1": "4dd4011d7e810981d49765458362d532616b7961",
          "md5": "b0eddabdf355be7b2d078dccbda84f46"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "reinforced-barrels-2.5.0+1.20-sources.jar",
          "url": "reinforced-barrels-2.5.0+1.20-sources.jar",
          "size": 59436,
          "sha512": "a0c44886dd85511a0ab5ddb3e1dde71047c7aa8be51defd16b34b7bbed62f3845e99dc7101cac53b4ff1460085846e66e3dd69d929a55c1a8345127ef6743c2a",
          "sha256": "7a70b8d96b0bbd6267a74cd237e49948defef8c2980b8fb9eee3852878c664e7",
          "sha1": "6d7e061f339923ee162af82ff029f26c0ade9755",
          "md5": "deac71441c5285062f627bbb1bc2d5b2"
        }
      ]
    }
  ]
}
