{
  "formatVersion": "1.1",
  "component": {
    "group": "atonkish.reinfshulker",
    "module": "reinforced-shulker-boxes",
    "version": "2.0.0-beta.2+1.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "reinforced-shulker-boxes-2.0.0-beta.2+1.18.jar",
          "url": "reinforced-shulker-boxes-2.0.0-beta.2+1.18.jar",
          "size": 437496,
          "sha512": "21ea4a6716d0901d8725b4787277ebe6c24c39e0a7b81a89b8aeaf1978a75ab2c7a109574fb581b21c30c014a56a89b610247c319cddf7bd637f6cfcbf339eff",
          "sha256": "b7559a2c5d241ebecff6024e584c744f88d00e26307fce86c97b4d163f1793d7",
          "sha1": "710f15f4a462c9980ed045b5c11ee1396c1490f1",
          "md5": "115dc9393087d09378db06d0e14cf2b9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "blue.endless",
          "module": "jankson",
          "version": {
            "requires": "1.2.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.27"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.13.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.4+1.18"
          }
        },
        {
          "group": "atonkish.reinfcore",
          "module": "reinforced-core",
          "version": {
            "requires": "2.0.0-beta.1+1.18"
          }
        },
        {
          "group": "atonkish.reinfchest",
          "module": "reinforced-chests",
          "version": {
            "requires": "2.0.0-beta.2+1.18"
          }
        },
        {
          "group": "net.kyrptonaught",
          "module": "quickshulker",
          "version": {
            "requires": "1.3.3-1.18"
          }
        },
        {
          "group": "com.misterpemodder",
          "module": "shulkerboxtooltip",
          "version": {
            "requires": "3.0.5+1.18"
          }
        }
      ],
      "files": [
        {
          "name": "reinforced-shulker-boxes-2.0.0-beta.2+1.18.jar",
          "url": "reinforced-shulker-boxes-2.0.0-beta.2+1.18.jar",
          "size": 437496,
          "sha512": "21ea4a6716d0901d8725b4787277ebe6c24c39e0a7b81a89b8aeaf1978a75ab2c7a109574fb581b21c30c014a56a89b610247c319cddf7bd637f6cfcbf339eff",
          "sha256": "b7559a2c5d241ebecff6024e584c744f88d00e26307fce86c97b4d163f1793d7",
          "sha1": "710f15f4a462c9980ed045b5c11ee1396c1490f1",
          "md5": "115dc9393087d09378db06d0e14cf2b9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "reinforced-shulker-boxes-2.0.0-beta.2+1.18-sources.jar",
          "url": "reinforced-shulker-boxes-2.0.0-beta.2+1.18-sources.jar",
          "size": 378936,
          "sha512": "9d476f5d743dd3659d7638259b0a5e89b0e87ade369899687b254c0d186fd0daf49d3fc79b890093726c20c67b127f12f286e73ca2a8174b5671789497206057",
          "sha256": "096b6dcc3c260c8364ffe9df1fe78cb8b404c15055fa384cf3db0262a8e5e459",
          "sha1": "4196608bbe2ab90650c3bf7d9415bbf9e4b3a3ec",
          "md5": "17444559a037eea670d5128cb6d8e8d7"
        }
      ]
    }
  ]
}
