{
  "formatVersion": "1.1",
  "component": {
    "group": "atonkish.reinfshulker",
    "module": "reinforced-shulker-boxes",
    "version": "2.2.0+1.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "reinforced-shulker-boxes-2.2.0+1.19.jar",
          "url": "reinforced-shulker-boxes-2.2.0+1.19.jar",
          "size": 1441865,
          "sha512": "5171988c03a88db47c67465d9b8159c9acf3b6b953818f67f18106e611f075a4bbc1aa5d7ac2ca7e27801aa58e937c8bea5c985cfdf412537a8bcceab2345f73",
          "sha256": "ecf780f6c72ef669c916de93b49b9a8de309ed8d7f0f883bf8e879788f237b35",
          "sha1": "bbd3a5965fc735b4827105b496ce06b853ec28a4",
          "md5": "9a07547bbdbeb19b08edc3ba5db23833"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "blue.endless",
          "module": "jankson",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.27"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.62.0+1.19.2"
          }
        },
        {
          "group": "atonkish.reinfcore",
          "module": "reinforced-core",
          "version": {
            "requires": "3.0.3+1.19"
          }
        },
        {
          "group": "atonkish.reinfchest",
          "module": "reinforced-chests",
          "version": {
            "requires": "2.2.0+1.19"
          }
        },
        {
          "group": "net.kyrptonaught",
          "module": "quickshulker",
          "version": {
            "requires": "1.3.9-1.19"
          }
        },
        {
          "group": "com.misterpemodder",
          "module": "shulkerboxtooltip",
          "version": {
            "requires": "3.0.10+1.19"
          }
        }
      ],
      "files": [
        {
          "name": "reinforced-shulker-boxes-2.2.0+1.19.jar",
          "url": "reinforced-shulker-boxes-2.2.0+1.19.jar",
          "size": 1441865,
          "sha512": "5171988c03a88db47c67465d9b8159c9acf3b6b953818f67f18106e611f075a4bbc1aa5d7ac2ca7e27801aa58e937c8bea5c985cfdf412537a8bcceab2345f73",
          "sha256": "ecf780f6c72ef669c916de93b49b9a8de309ed8d7f0f883bf8e879788f237b35",
          "sha1": "bbd3a5965fc735b4827105b496ce06b853ec28a4",
          "md5": "9a07547bbdbeb19b08edc3ba5db23833"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "reinforced-shulker-boxes-2.2.0+1.19-sources.jar",
          "url": "reinforced-shulker-boxes-2.2.0+1.19-sources.jar",
          "size": 382220,
          "sha512": "0f50d5c8af874eec22df66054db785f689b7319e3819a9d14a1385d36c25f0107e309c321967f50c4d6c699627a46b5650b5379b4161ceeea93d7a35462cc725",
          "sha256": "d8e628f71278c028f6644ed2a3cbef2b8c81ddddcf7e338da6a370e65ad16c28",
          "sha1": "115cfe8a9f2f9ef3c6aaa850c6c30fe6da8e4f3d",
          "md5": "cdf3ff49b47da68fe33a04da3970195c"
        }
      ]
    }
  ]
}
