{
  "formatVersion": "1.1",
  "component": {
    "group": "atonkish.reinfbarrel",
    "module": "reinforced-barrels",
    "version": "1.0.6+1.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "reinforced-barrels-1.0.6+1.18.jar",
          "url": "reinforced-barrels-1.0.6+1.18.jar",
          "size": 77620,
          "sha512": "ae9d4b895d38028ec8f5467a716c7b81dc23b2b392ad49a3e565fa3efdfe4e7a217568a85c2181f7cb3867c25ac00bd3114b57cfae7bbf9c67896797f4479b5c",
          "sha256": "15637a6e72d01e64c3c4ebbd6c299bc033b485e0c6accec266c829903a035244",
          "sha1": "5bcf39095024c0efb3a527b17bb231f2d07176bf",
          "md5": "746b512b45f4b1df1c7548d2d2a0f9fe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.12.12"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.1+1.18"
          }
        },
        {
          "group": "atonkish.reinfcore",
          "module": "reinforced-core",
          "version": {
            "requires": "1.1.3+1.18"
          }
        }
      ],
      "files": [
        {
          "name": "reinforced-barrels-1.0.6+1.18.jar",
          "url": "reinforced-barrels-1.0.6+1.18.jar",
          "size": 77620,
          "sha512": "ae9d4b895d38028ec8f5467a716c7b81dc23b2b392ad49a3e565fa3efdfe4e7a217568a85c2181f7cb3867c25ac00bd3114b57cfae7bbf9c67896797f4479b5c",
          "sha256": "15637a6e72d01e64c3c4ebbd6c299bc033b485e0c6accec266c829903a035244",
          "sha1": "5bcf39095024c0efb3a527b17bb231f2d07176bf",
          "md5": "746b512b45f4b1df1c7548d2d2a0f9fe"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "reinforced-barrels-1.0.6+1.18-sources.jar",
          "url": "reinforced-barrels-1.0.6+1.18-sources.jar",
          "size": 40523,
          "sha512": "1140b8b31d169a00b38f8418066ab1699e2cd91ffef11f618890c4e0b799b960bcf528757b0457490d24d3cb46fd29d17b8f540dbbe13a8d67530bfc3ee777e8",
          "sha256": "e04bf093c1788936309a9757b16e82165ecf35d4bc218017711f838647ec44b0",
          "sha1": "09b03873bd94c69220659df743123964ad89a0d2",
          "md5": "69df772a195be63c6fb61cfcff8b3b1a"
        }
      ]
    }
  ]
}
