{
  "formatVersion": "1.1",
  "component": {
    "group": "atonkish.reinfshulker",
    "module": "reinforced-shulker-boxes",
    "version": "2.4.1+1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "reinforced-shulker-boxes-2.4.1+1.20.jar",
          "url": "reinforced-shulker-boxes-2.4.1+1.20.jar",
          "size": 1452489,
          "sha512": "48b1060704574704d20def63160ae3e6296c04eaf0e6c16aef96c50475a1ce4cdf476724def7bc262ae6bbc5f0dc1816aeed017962dc08a4f20fd1b7eef631fc",
          "sha256": "51fb232e6797f7415cb4562624760b4a217c78db67f85df2a56d0faff05edfea",
          "sha1": "2b1a34428f120c8ae96aa603d113e977effb9b6f",
          "md5": "6ba1e574ddf8af0305317d1b4b027fd7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.83.1+1.20.1"
          }
        },
        {
          "group": "atonkish.reinfcore",
          "module": "reinforced-core",
          "version": {
            "requires": "3.1.2+1.20"
          }
        },
        {
          "group": "atonkish.reinfchest",
          "module": "reinforced-chests",
          "version": {
            "requires": "2.4.2+1.20"
          }
        },
        {
          "group": "net.kyrptonaught",
          "module": "quickshulker",
          "version": {
            "requires": "1.4.0-1.20"
          }
        },
        {
          "group": "net.kyrptonaught",
          "module": "shulkerutils",
          "version": {
            "requires": "1.0.4-1.19"
          }
        },
        {
          "group": "com.misterpemodder",
          "module": "shulkerboxtooltip-fabric",
          "version": {
            "requires": "4.0.3+1.20"
          }
        }
      ],
      "files": [
        {
          "name": "reinforced-shulker-boxes-2.4.1+1.20.jar",
          "url": "reinforced-shulker-boxes-2.4.1+1.20.jar",
          "size": 1452489,
          "sha512": "48b1060704574704d20def63160ae3e6296c04eaf0e6c16aef96c50475a1ce4cdf476724def7bc262ae6bbc5f0dc1816aeed017962dc08a4f20fd1b7eef631fc",
          "sha256": "51fb232e6797f7415cb4562624760b4a217c78db67f85df2a56d0faff05edfea",
          "sha1": "2b1a34428f120c8ae96aa603d113e977effb9b6f",
          "md5": "6ba1e574ddf8af0305317d1b4b027fd7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
