{
  "formatVersion": "1.1",
  "component": {
    "group": "atonkish.reinfcore",
    "module": "reinforced-core",
    "version": "3.0.1+1.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "blue.endless",
          "module": "jankson",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.27"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "8.0.75"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "reinforced-core-3.0.1+1.19.jar",
          "url": "reinforced-core-3.0.1+1.19.jar",
          "size": 41001,
          "sha512": "6add4219706ecff4e4b636597a5c8db3ece315c12dbeb8bca5c86de13c2019b2057fd4eb016bd645940285016d51b2ec56de00ba9f4ba5fae20479b9962b1376",
          "sha256": "b1d8f1758c5d0a8cf9dbb2f8f9cb4b853caadf2e3df360bad887a881bed67436",
          "sha1": "fa3a6f7b614ffd5539bffcd4c6f29284be2cecc6",
          "md5": "96068b485148f94e785412f293c50f3f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "blue.endless",
          "module": "jankson",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.27"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "8.0.75"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.59.0+1.19.2"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "4.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "reinforced-core-3.0.1+1.19.jar",
          "url": "reinforced-core-3.0.1+1.19.jar",
          "size": 41001,
          "sha512": "6add4219706ecff4e4b636597a5c8db3ece315c12dbeb8bca5c86de13c2019b2057fd4eb016bd645940285016d51b2ec56de00ba9f4ba5fae20479b9962b1376",
          "sha256": "b1d8f1758c5d0a8cf9dbb2f8f9cb4b853caadf2e3df360bad887a881bed67436",
          "sha1": "fa3a6f7b614ffd5539bffcd4c6f29284be2cecc6",
          "md5": "96068b485148f94e785412f293c50f3f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "reinforced-core-3.0.1+1.19-sources.jar",
          "url": "reinforced-core-3.0.1+1.19-sources.jar",
          "size": 27875,
          "sha512": "32ea978b4633425fa59273062f80ab373e614ef7d635c0fa2373c8a95d60f2981be5a63332b6bab908ddeb52dacb154bda491e48ba913fd0d1fde664d5ca692d",
          "sha256": "51201b5361126f2fdf32c9b4b9ff70fac8c4ac3e9317ae764e1fa39be1ae733b",
          "sha1": "d04d613d3a8269de7b823d57291205277d24f406",
          "md5": "095c8bd1024429b39956a89a79e3dddc"
        }
      ]
    }
  ]
}
