{
  "formatVersion": "1.1",
  "component": {
    "group": "atonkish.reinfshulker",
    "module": "reinforced-shulker-boxes",
    "version": "3.0.1+1.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "reinforced-shulker-boxes-3.0.1+1.21.jar",
          "url": "reinforced-shulker-boxes-3.0.1+1.21.jar",
          "size": 1470689,
          "sha512": "14fad1e3a217e557ac59479be601c6c914dff967105aaec36dff5bb430b9affe2bc5bd9471ca2f8cda14b9f8df953beef8c3be40b1195b3613795e0de74fcdc5",
          "sha256": "aef8eb6a7baa06749b55b794b4ad50561b64617bf885bb973481f529e002155f",
          "sha1": "99f3e0a38e09b45063f2fc89b7955f3a7d9464a1",
          "md5": "b4eab5c4205fff65edb8376220db148f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.100.1+1.21"
          }
        },
        {
          "group": "atonkish.reinfcore",
          "module": "reinforced-core",
          "version": {
            "requires": "4.0.1+1.21"
          }
        },
        {
          "group": "atonkish.reinfchest",
          "module": "reinforced-chests",
          "version": {
            "requires": "3.0.1+1.21"
          }
        }
      ],
      "files": [
        {
          "name": "reinforced-shulker-boxes-3.0.1+1.21.jar",
          "url": "reinforced-shulker-boxes-3.0.1+1.21.jar",
          "size": 1470689,
          "sha512": "14fad1e3a217e557ac59479be601c6c914dff967105aaec36dff5bb430b9affe2bc5bd9471ca2f8cda14b9f8df953beef8c3be40b1195b3613795e0de74fcdc5",
          "sha256": "aef8eb6a7baa06749b55b794b4ad50561b64617bf885bb973481f529e002155f",
          "sha1": "99f3e0a38e09b45063f2fc89b7955f3a7d9464a1",
          "md5": "b4eab5c4205fff65edb8376220db148f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "reinforced-shulker-boxes-3.0.1+1.21-sources.jar",
          "url": "reinforced-shulker-boxes-3.0.1+1.21-sources.jar",
          "size": 391050,
          "sha512": "d957a8986f898d371c4a54a388863ad9a585c2238d76d2f997a754eb4ed7b614166d87e503751b7688763f4babce7e93abdaf61783d76b726a433ad18a99e9a0",
          "sha256": "0eb18a39fe3d98822b028d6ad26dd2feb233c435d4626f2103b198baaa286574",
          "sha1": "82372cd211ff4300aaac893483a7251c66cec66c",
          "md5": "93afbb1c3c2dc1495cde95e7af476bca"
        }
      ]
    }
  ]
}
