{
  "formatVersion": "1.1",
  "component": {
    "group": "atonkish.reinfshulker",
    "module": "reinforced-shulker-boxes",
    "version": "1.1.5+1.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "reinforced-shulker-boxes-1.1.5+1.18.jar",
          "url": "reinforced-shulker-boxes-1.1.5+1.18.jar",
          "size": 425076,
          "sha512": "75970ff2f830dc0a2e3ec64ffbc0567eacfdd50c97d2efee108081a08aba8dd3d1a7f9d1708454639d5f61f38f5f1cd6ef862c67291389f09460e257b7039f57",
          "sha256": "c15cf1d3cb245774db9e1adabc4838496a71d07375a7eb82112ee81e00836b1b",
          "sha1": "6db4f7e7273e30f12e72eed15a46cd3ffeb10d60",
          "md5": "1b4597c303763621f9bc70155d108052"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "blue.endless",
          "module": "jankson",
          "version": {
            "requires": "1.2.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.27"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.12.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.44.0+1.18"
          }
        },
        {
          "group": "atonkish.reinfcore",
          "module": "reinforced-core",
          "version": {
            "requires": "1.1.2+1.18"
          }
        },
        {
          "group": "net.kyrptonaught",
          "module": "quickshulker",
          "version": {
            "requires": "1.3.1-1.18"
          }
        },
        {
          "group": "com.misterpemodder",
          "module": "shulkerboxtooltip",
          "version": {
            "requires": "3.0.5+1.18"
          }
        }
      ],
      "files": [
        {
          "name": "reinforced-shulker-boxes-1.1.5+1.18.jar",
          "url": "reinforced-shulker-boxes-1.1.5+1.18.jar",
          "size": 425076,
          "sha512": "75970ff2f830dc0a2e3ec64ffbc0567eacfdd50c97d2efee108081a08aba8dd3d1a7f9d1708454639d5f61f38f5f1cd6ef862c67291389f09460e257b7039f57",
          "sha256": "c15cf1d3cb245774db9e1adabc4838496a71d07375a7eb82112ee81e00836b1b",
          "sha1": "6db4f7e7273e30f12e72eed15a46cd3ffeb10d60",
          "md5": "1b4597c303763621f9bc70155d108052"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "reinforced-shulker-boxes-1.1.5+1.18-sources.jar",
          "url": "reinforced-shulker-boxes-1.1.5+1.18-sources.jar",
          "size": 373359,
          "sha512": "5fbb68baa07cb2d2f88faffbd12483d97a4105f60999202be99b3b287a6bd3f18e25519447fa56bf173e09c55dac19a1c00e8f28e62f94935b9f3a4dbb723275",
          "sha256": "152dd6044aee409ff5a1e4f1408d8b05e8f11b59fc876bc62947e08a1408d6ad",
          "sha1": "aa6030689ed21db043fc3eaab46aa47f277bae67",
          "md5": "20ec71ccf93a63ed012c5f0cb577b683"
        }
      ]
    }
  ]
}
