{
  "formatVersion": "1.1",
  "component": {
    "group": "atonkish.reinfbarrel",
    "module": "reinforced-barrels",
    "version": "2.4.2+1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "reinforced-barrels-2.4.2+1.20.jar",
          "url": "reinforced-barrels-2.4.2+1.20.jar",
          "size": 1091851,
          "sha512": "e1d7ea34f902bb999a74d90db167d9ecdcddb03cc9830771987a626c0071906adbaf78adb2e3d7546cd7e63113a9234ffb991c4ce070f16b1fcb84b43a68d73d",
          "sha256": "fc805ccfa8bd304aba05635544170966695ccf6a3190ed140205f41f774c2130",
          "sha1": "abe716d289db04f5983479498e38c6aa2cd3bc8b",
          "md5": "4ba4f504910781e54b7fe54451c67795"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.91.1+1.20.4"
          }
        },
        {
          "group": "atonkish.reinfcore",
          "module": "reinforced-core",
          "version": {
            "requires": "3.1.3+1.20"
          }
        }
      ],
      "files": [
        {
          "name": "reinforced-barrels-2.4.2+1.20.jar",
          "url": "reinforced-barrels-2.4.2+1.20.jar",
          "size": 1091851,
          "sha512": "e1d7ea34f902bb999a74d90db167d9ecdcddb03cc9830771987a626c0071906adbaf78adb2e3d7546cd7e63113a9234ffb991c4ce070f16b1fcb84b43a68d73d",
          "sha256": "fc805ccfa8bd304aba05635544170966695ccf6a3190ed140205f41f774c2130",
          "sha1": "abe716d289db04f5983479498e38c6aa2cd3bc8b",
          "md5": "4ba4f504910781e54b7fe54451c67795"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
