{
  "formatVersion": "1.1",
  "component": {
    "group": "atonkish.reinfcore",
    "module": "reinforced-core",
    "version": "3.1.3+1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "13.0.114"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "reinforced-core-3.1.3+1.20.jar",
          "url": "reinforced-core-3.1.3+1.20.jar",
          "size": 1042644,
          "sha512": "f7c468a0d87ca61e49fe2bbe5f4beab91816846ed0adddb645c2c492e85ba6e5e7dcd1bdd14d82d5bb41ac55fbb67127dbadcc4708c81ec7a8d4c627f098fc23",
          "sha256": "a6c9a5bf3532ef08e219c7a4b395c948b0d5a6e7310aa53982ef8f465b23f721",
          "sha1": "108b98dd7c17d405e552b0b60fb798a0271448df",
          "md5": "28b7bb14b74c142cdbbc5c53068a9ad3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "13.0.114"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.91.1+1.20.4"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "9.0.0-pre.1"
          }
        }
      ],
      "files": [
        {
          "name": "reinforced-core-3.1.3+1.20.jar",
          "url": "reinforced-core-3.1.3+1.20.jar",
          "size": 1042644,
          "sha512": "f7c468a0d87ca61e49fe2bbe5f4beab91816846ed0adddb645c2c492e85ba6e5e7dcd1bdd14d82d5bb41ac55fbb67127dbadcc4708c81ec7a8d4c627f098fc23",
          "sha256": "a6c9a5bf3532ef08e219c7a4b395c948b0d5a6e7310aa53982ef8f465b23f721",
          "sha1": "108b98dd7c17d405e552b0b60fb798a0271448df",
          "md5": "28b7bb14b74c142cdbbc5c53068a9ad3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
