{
  "formatVersion": "1.1",
  "component": {
    "group": "atonkish.reinfcore",
    "module": "reinforced-core",
    "version": "3.1.1+1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "11.0.98"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "reinforced-core-3.1.1+1.20.jar",
          "url": "reinforced-core-3.1.1+1.20.jar",
          "size": 1042553,
          "sha512": "40f8e497c9cd9ed7cb61e66d26875abe47de080960ce9feaaeeddcfcded59cc14d505c33a3a133ff1b2bb63176d09fa4f82d3c899adfe78038c7fbe922d20256",
          "sha256": "e46bb4cdaec3dc5de2adaa000664e0ec9d03a73367890788627d0e2b222462c2",
          "sha1": "7cef449fcb9dcdbb33eb556e46f3bc225a51c74e",
          "md5": "094c347632c3ff59447e978aa119fdb9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "11.0.98"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.83.0+1.20"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "reinforced-core-3.1.1+1.20.jar",
          "url": "reinforced-core-3.1.1+1.20.jar",
          "size": 1042553,
          "sha512": "40f8e497c9cd9ed7cb61e66d26875abe47de080960ce9feaaeeddcfcded59cc14d505c33a3a133ff1b2bb63176d09fa4f82d3c899adfe78038c7fbe922d20256",
          "sha256": "e46bb4cdaec3dc5de2adaa000664e0ec9d03a73367890788627d0e2b222462c2",
          "sha1": "7cef449fcb9dcdbb33eb556e46f3bc225a51c74e",
          "md5": "094c347632c3ff59447e978aa119fdb9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
