{
  "formatVersion": "1.1",
  "component": {
    "group": "atonkish.reinfshulker",
    "module": "reinforced-shulker-boxes",
    "version": "2.1.0+1.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "reinforced-shulker-boxes-2.1.0+1.19.jar",
          "url": "reinforced-shulker-boxes-2.1.0+1.19.jar",
          "size": 442922,
          "sha512": "23fdec58837f300e2c9484e858681226c9f1954b2e31cd8d9048cf4637f16420effa42de8290df8847fe881ff689fed9d8fe92d9300aa774026bf6e1c2a97063",
          "sha256": "047512d10a87d5d59bd1365fbf959af9a0f97002ddbd6d05990d7c469c710272",
          "sha1": "b5b9286dd953bc862568c9f616692618260141f5",
          "md5": "e4ae5b7c5cb1fd98d7af62053f716126"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "blue.endless",
          "module": "jankson",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.27"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.59.0+1.19.2"
          }
        },
        {
          "group": "atonkish.reinfcore",
          "module": "reinforced-core",
          "version": {
            "requires": "3.0.1+1.19"
          }
        },
        {
          "group": "atonkish.reinfchest",
          "module": "reinforced-chests",
          "version": {
            "requires": "2.1.1+1.19"
          }
        },
        {
          "group": "net.kyrptonaught",
          "module": "quickshulker",
          "version": {
            "requires": "1.3.7-1.19"
          }
        },
        {
          "group": "com.misterpemodder",
          "module": "shulkerboxtooltip",
          "version": {
            "requires": "3.0.10+1.19"
          }
        }
      ],
      "files": [
        {
          "name": "reinforced-shulker-boxes-2.1.0+1.19.jar",
          "url": "reinforced-shulker-boxes-2.1.0+1.19.jar",
          "size": 442922,
          "sha512": "23fdec58837f300e2c9484e858681226c9f1954b2e31cd8d9048cf4637f16420effa42de8290df8847fe881ff689fed9d8fe92d9300aa774026bf6e1c2a97063",
          "sha256": "047512d10a87d5d59bd1365fbf959af9a0f97002ddbd6d05990d7c469c710272",
          "sha1": "b5b9286dd953bc862568c9f616692618260141f5",
          "md5": "e4ae5b7c5cb1fd98d7af62053f716126"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "reinforced-shulker-boxes-2.1.0+1.19-sources.jar",
          "url": "reinforced-shulker-boxes-2.1.0+1.19-sources.jar",
          "size": 378863,
          "sha512": "8dc78e9eef542a1a7766d9793502d63ab085f41a52c0103e75e9d9ecd9250f3ce4d575cae40c260ecd6e9e3db9b77569084811f44999a38f3eea611cbc70826a",
          "sha256": "71898ca06d9f19f3563bc17fbc5abc3474db3f449025bc91a6a26e04894eb189",
          "sha1": "62291ab354ee577061b5d33d6f3f644c1f79fd36",
          "md5": "f0a2f0f9fcbc66fafd43b2251ab00177"
        }
      ]
    }
  ]
}
