{
  "formatVersion": "1.1",
  "component": {
    "group": "atonkish.reinfchest",
    "module": "reinforced-chests",
    "version": "3.0.0+1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "reinforced-chests-3.0.0+1.20.jar",
          "url": "reinforced-chests-3.0.0+1.20.jar",
          "size": 1159553,
          "sha512": "06e5ba6f271be3b43c5e63878db0fb2b324a6f25edb63c8ceaaa29cc5d8d036d5dbc455dce70915c3857487b2b9527ee48e8e262bb7bb385bcd65c1c67fd6c82",
          "sha256": "0842ceb90f44b9d25c5c630dfa9febb2dc58c98cb6828813a4f8e1e71fbe2c4e",
          "sha1": "93f31ad7363a5dbd602eb8a55c9c5ecb49b00462",
          "md5": "12de284a64d4903f691df4e0d7ba7dbd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.100.0+1.20.6"
          }
        },
        {
          "group": "atonkish.reinfcore",
          "module": "reinforced-core",
          "version": {
            "requires": "4.0.0+1.20"
          }
        }
      ],
      "files": [
        {
          "name": "reinforced-chests-3.0.0+1.20.jar",
          "url": "reinforced-chests-3.0.0+1.20.jar",
          "size": 1159553,
          "sha512": "06e5ba6f271be3b43c5e63878db0fb2b324a6f25edb63c8ceaaa29cc5d8d036d5dbc455dce70915c3857487b2b9527ee48e8e262bb7bb385bcd65c1c67fd6c82",
          "sha256": "0842ceb90f44b9d25c5c630dfa9febb2dc58c98cb6828813a4f8e1e71fbe2c4e",
          "sha1": "93f31ad7363a5dbd602eb8a55c9c5ecb49b00462",
          "md5": "12de284a64d4903f691df4e0d7ba7dbd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "reinforced-chests-3.0.0+1.20-sources.jar",
          "url": "reinforced-chests-3.0.0+1.20-sources.jar",
          "size": 85690,
          "sha512": "60117bea0c9ad26aa6dcb1a57ab0e6905264e44d93b52c681c35baa7b7e659ff66c47b34e13f3261dfcd50f305f3fbc8ddde750bfafd31a1932ab36309849bac",
          "sha256": "bf19919c888c04fb567fbe1272cc66f2ad352364573060b78d67760bd8212c5d",
          "sha1": "4a9e344069be619afb6de923cf9c964afff0945f",
          "md5": "848944d444039444ec3f0ceaec28b7dd"
        }
      ]
    }
  ]
}
