{
  "formatVersion": "1.1",
  "component": {
    "group": "atonkish.reinfcore",
    "module": "reinforced-core",
    "version": "1.1.3+1.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "reinforced-core-1.1.3+1.18.jar",
          "url": "reinforced-core-1.1.3+1.18.jar",
          "size": 31604,
          "sha512": "7f5df01ea46236789696fdb8110d4ae5681996d393bdc7d5b237d5027a4b44bfd7943fc475f58a32a2548ffb969c31403d475f3703351613647532d9e947c7da",
          "sha256": "84778cde62b19df6cedeac893f5ee078bea1a207badc969dde086f6a8f7a481f",
          "sha1": "53c0486cf4332e02cf53ced387e4d2b0c01d48de",
          "md5": "24bccdd71ad068a9e715091818dd02c4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.12.12"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.1+1.18"
          }
        }
      ],
      "files": [
        {
          "name": "reinforced-core-1.1.3+1.18.jar",
          "url": "reinforced-core-1.1.3+1.18.jar",
          "size": 31604,
          "sha512": "7f5df01ea46236789696fdb8110d4ae5681996d393bdc7d5b237d5027a4b44bfd7943fc475f58a32a2548ffb969c31403d475f3703351613647532d9e947c7da",
          "sha256": "84778cde62b19df6cedeac893f5ee078bea1a207badc969dde086f6a8f7a481f",
          "sha1": "53c0486cf4332e02cf53ced387e4d2b0c01d48de",
          "md5": "24bccdd71ad068a9e715091818dd02c4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "reinforced-core-1.1.3+1.18-sources.jar",
          "url": "reinforced-core-1.1.3+1.18-sources.jar",
          "size": 22872,
          "sha512": "47aa3b929360b37f264d18eddce8ba4ceb8556f150931c06627f525088c3d6cb69b1b1c972c4854aefdf2c78a026a90f85cb6a6b369b09260811fde970d78f1e",
          "sha256": "79e6489c7ca02d9e00811d559085ba993664be927eacba3f4008d3804df095c5",
          "sha1": "f717874b3c149c87be8322aef3123f24757d8a9d",
          "md5": "15a75cedc918802aff93050296ed6f40"
        }
      ]
    }
  ]
}
